# Generated by Django 4.1.4 on 2023-02-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='area',
            new_name='place',
        ),
    ]
